/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: wifi_scan_res.proto */

#ifndef PROTOBUF_C_wifi_5fscan_5fres_2eproto__INCLUDED
#define PROTOBUF_C_wifi_5fscan_5fres_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct WiFiNetwork WiFiNetwork;
typedef struct WiFiScanResults WiFiScanResults;


/* --- enums --- */


/* --- messages --- */

struct  WiFiNetwork
{
  ProtobufCMessage base;
  char *ssid;
  int32_t rssi;
  int32_t channel;
  char *auth;
};
#define WI_FI_NETWORK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wi_fi_network__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


struct  WiFiScanResults
{
  ProtobufCMessage base;
  size_t n_networks;
  WiFiNetwork **networks;
};
#define WI_FI_SCAN_RESULTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wi_fi_scan_results__descriptor) \
, 0,NULL }


/* WiFiNetwork methods */
void   wi_fi_network__init
                     (WiFiNetwork         *message);
size_t wi_fi_network__get_packed_size
                     (const WiFiNetwork   *message);
size_t wi_fi_network__pack
                     (const WiFiNetwork   *message,
                      uint8_t             *out);
size_t wi_fi_network__pack_to_buffer
                     (const WiFiNetwork   *message,
                      ProtobufCBuffer     *buffer);
WiFiNetwork *
       wi_fi_network__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wi_fi_network__free_unpacked
                     (WiFiNetwork *message,
                      ProtobufCAllocator *allocator);
/* WiFiScanResults methods */
void   wi_fi_scan_results__init
                     (WiFiScanResults         *message);
size_t wi_fi_scan_results__get_packed_size
                     (const WiFiScanResults   *message);
size_t wi_fi_scan_results__pack
                     (const WiFiScanResults   *message,
                      uint8_t             *out);
size_t wi_fi_scan_results__pack_to_buffer
                     (const WiFiScanResults   *message,
                      ProtobufCBuffer     *buffer);
WiFiScanResults *
       wi_fi_scan_results__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wi_fi_scan_results__free_unpacked
                     (WiFiScanResults *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*WiFiNetwork_Closure)
                 (const WiFiNetwork *message,
                  void *closure_data);
typedef void (*WiFiScanResults_Closure)
                 (const WiFiScanResults *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor wi_fi_network__descriptor;
extern const ProtobufCMessageDescriptor wi_fi_scan_results__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_wifi_5fscan_5fres_2eproto__INCLUDED */
