/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: wifi_scan_res.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "wifi_scan_res.pb-c.h"
void   wi_fi_network__init
                     (WiFiNetwork         *message)
{
  static const WiFiNetwork init_value = WI_FI_NETWORK__INIT;
  *message = init_value;
}
size_t wi_fi_network__get_packed_size
                     (const WiFiNetwork *message)
{
  assert(message->base.descriptor == &wi_fi_network__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wi_fi_network__pack
                     (const WiFiNetwork *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wi_fi_network__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wi_fi_network__pack_to_buffer
                     (const WiFiNetwork *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wi_fi_network__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WiFiNetwork *
       wi_fi_network__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WiFiNetwork *)
     protobuf_c_message_unpack (&wi_fi_network__descriptor,
                                allocator, len, data);
}
void   wi_fi_network__free_unpacked
                     (WiFiNetwork *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wi_fi_network__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wi_fi_scan_results__init
                     (WiFiScanResults         *message)
{
  static const WiFiScanResults init_value = WI_FI_SCAN_RESULTS__INIT;
  *message = init_value;
}
size_t wi_fi_scan_results__get_packed_size
                     (const WiFiScanResults *message)
{
  assert(message->base.descriptor == &wi_fi_scan_results__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wi_fi_scan_results__pack
                     (const WiFiScanResults *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wi_fi_scan_results__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wi_fi_scan_results__pack_to_buffer
                     (const WiFiScanResults *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wi_fi_scan_results__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WiFiScanResults *
       wi_fi_scan_results__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WiFiScanResults *)
     protobuf_c_message_unpack (&wi_fi_scan_results__descriptor,
                                allocator, len, data);
}
void   wi_fi_scan_results__free_unpacked
                     (WiFiScanResults *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wi_fi_scan_results__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wi_fi_network__field_descriptors[4] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WiFiNetwork, ssid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WiFiNetwork, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WiFiNetwork, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(WiFiNetwork, auth),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wi_fi_network__field_indices_by_name[] = {
  3,   /* field[3] = auth */
  2,   /* field[2] = channel */
  1,   /* field[1] = rssi */
  0,   /* field[0] = ssid */
};
static const ProtobufCIntRange wi_fi_network__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor wi_fi_network__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WiFiNetwork",
  "WiFiNetwork",
  "WiFiNetwork",
  "",
  sizeof(WiFiNetwork),
  4,
  wi_fi_network__field_descriptors,
  wi_fi_network__field_indices_by_name,
  1,  wi_fi_network__number_ranges,
  (ProtobufCMessageInit) wi_fi_network__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wi_fi_scan_results__field_descriptors[1] =
{
  {
    "networks",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WiFiScanResults, n_networks),
    offsetof(WiFiScanResults, networks),
    &wi_fi_network__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wi_fi_scan_results__field_indices_by_name[] = {
  0,   /* field[0] = networks */
};
static const ProtobufCIntRange wi_fi_scan_results__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor wi_fi_scan_results__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WiFiScanResults",
  "WiFiScanResults",
  "WiFiScanResults",
  "",
  sizeof(WiFiScanResults),
  1,
  wi_fi_scan_results__field_descriptors,
  wi_fi_scan_results__field_indices_by_name,
  1,  wi_fi_scan_results__number_ranges,
  (ProtobufCMessageInit) wi_fi_scan_results__init,
  NULL,NULL,NULL    /* reserved[123] */
};
